import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";
import { currentUser } from "@clerk/nextjs/server";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Home() {
  const user = await currentUser();
  const username = user?.username;

  return (
    <ClerkProvider>
      <div className="flex flex-col items-center justify-between w-full flex-1">
        <div className="flex flex-row items-center justify-end w-full h-10 min-h-6">
          <div className="mr-3 mt-2">
            <SignedIn>
              <UserButton />
            </SignedIn>
          </div>
        </div>

        <div className="flex flex-col flex-grow items-start justify-center w-full">
          <div className="flex flex-row items-center justify-center gap-5 w-full">
            <span className="text-4xl font-bold items-center">
              Welcome to Synaptic AI
            </span>
          </div>

          <div className="flex flex-row items-center justify-center gap-5 w-full pt-5">
            {username && <div>Hello {username} 👋!</div>}
          </div>

          <SignedOut>
            <div className="flex flex-row gap-4 items-center justify-center w-full">
              <SignInButton mode="modal">
                <button className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600">
                  Sign In
                </button>
              </SignInButton>
              <SignUpButton mode="modal">
                <button className="px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600">
                  Sign Up
                </button>
              </SignUpButton>
            </div>
          </SignedOut>
        </div>
        
      </div>
    </ClerkProvider>
  );
}
